# Generated by Django 5.0.2 on 2025-05-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=20)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('publico_objetivo', models.CharField(choices=[('Estudiantes', 'Estudiantes'), ('Profesores', 'Profesores'), ('Publico general', 'Público general')], max_length=20)),
                ('programa_educativo', models.CharField(blank=True, choices=[('Ingeniería en Ciencias de la Computación', 'Ingeniería en Ciencias de la Computación'), ('Licenciatura en Ciencias de la Computación', 'Licenciatura en Ciencias de la Computación'), ('Ingeniería en Tecnologías de la Información', 'Ingeniería en Tecnologías de la Información')], max_length=50, null=True)),
                ('descripcion_breve', models.CharField(max_length=300)),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('responsable_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_admin', to='crud_escolar_api.administradores')),
                ('responsable_maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_maestro', to='crud_escolar_api.maestros')),
            ],
        ),
    ]
