# Generated by Django 5.0.2 on 2025-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_eventoacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacademico',
            name='publico_objetivo',
            field=models.CharField(choices=[('Estudiantes', 'Estudiantes'), ('Profesores', 'Profesores'), ('Publico general', 'Publico general')], max_length=20),
        ),
    ]
