# Generated by Django 5.0.2 on 2025-05-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0005_alter_eventoacademico_publico_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasEventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('cantidad_registros', models.IntegerField(default=0)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
