# Generated by Django 5.0.2 on 2025-05-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0006_estadisticaseventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticaseventos',
            old_name='cantidad_registros',
            new_name='cantidad_eventos',
        ),
        migrations.AddField(
            model_name='estadisticaseventos',
            name='mes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='estadisticaseventos',
            index=models.Index(fields=['mes'], name='crud_escola_mes_11e38d_idx'),
        ),
        migrations.AddIndex(
            model_name='estadisticaseventos',
            index=models.Index(fields=['tipo_evento'], name='crud_escola_tipo_ev_6a865b_idx'),
        ),
    ]
